name: Automate Re-deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote to Contabo VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 84.247.173.20
          username: root
          key: ${{ secrets.CONTAO_KEY }}
          port: 1308
          script: |
            whomai
            pwd
